/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5SdMxI1xz4F
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"

export function JobDetail() {
  return (
    <div className="max-w-6xl mx-auto py-8 px-4 md:px-6">
      <div className="grid gap-8">
        <div className="grid gap-4">
          <h1 className="text-3xl font-bold">Senior Frontend Developer</h1>
          <div className="grid sm:grid-cols-2 gap-4">
            <div className="grid gap-1">
              <div className="text-sm font-medium text-muted-foreground">Job Code</div>
              <div>FE-123</div>
            </div>
            <div className="grid gap-1">
              <div className="text-sm font-medium text-muted-foreground">Location</div>
              <div>Remote</div>
            </div>
          </div>
        </div>
        <div className="grid gap-6">
          <div className="grid gap-2">
            <h2 className="text-xl font-semibold">Job Description</h2>
            <div className="text-muted-foreground">
              We are looking for an experienced Frontend Developer to join our team. You will be responsible for
              building and maintaining high-quality web applications using the latest technologies and best practices.
            </div>
          </div>
          <div className="grid gap-2">
            <h2 className="text-xl font-semibold">Requirements</h2>
            <ul className="grid gap-2 text-muted-foreground">
              <li>
                - 5+ years of experience in frontend development using JavaScript, React, and related technologies
              </li>
              <li>- Strong understanding of HTML, CSS, and responsive design principles</li>
              <li>- Experience with state management libraries like Redux or MobX</li>
              <li>- Familiarity with testing frameworks like Jest and Enzyme</li>
              <li>- Excellent problem-solving and analytical skills</li>
            </ul>
          </div>
          <div className="grid gap-2">
            <h2 className="text-xl font-semibold">Benefits</h2>
            <ul className="grid gap-2 text-muted-foreground">
              <li>- Competitive salary and bonus structure</li>
              <li>- Comprehensive health insurance package</li>
              <li>- 401(k) retirement plan with employer matching</li>
              <li>- Generous paid time off and holidays</li>
              <li>- Professional development opportunities</li>
            </ul>
          </div>
          <div className="grid gap-2">
            <h2 className="text-xl font-semibold">Employment Type</h2>
            <div className="text-muted-foreground">Full-time</div>
          </div>
        </div>
        <div className="grid gap-6">
          <h2 className="text-xl font-semibold">Candidates</h2>
          <div className="grid gap-4">
            <div className="grid gap-4 border rounded-lg p-4">
              <div className="flex items-center gap-4">
                <Avatar className="w-12 h-12">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-semibold">John Doe</div>
                  <div className="text-sm text-muted-foreground">7 years of experience</div>
                </div>
                <div className="ml-auto flex items-center gap-2">
                  <div className="text-sm font-medium">Relevancy Score</div>
                  <div className="flex items-center gap-1">
                    <div className="w-16 h-4 rounded-full bg-muted">
                      <div className="h-full w-3/4 rounded-full bg-primary" />
                    </div>
                    <div className="text-sm font-medium">75%</div>
                  </div>
                </div>
              </div>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center gap-2 font-medium [&[data-state=open]>svg]:rotate-90">
                  Career Summary
                  <ChevronRightIcon className="w-4 h-4 transition-all" />
                </CollapsibleTrigger>
                <CollapsibleContent>
                  <div className="text-muted-foreground">
                    John is an experienced frontend developer with a strong background in React, Redux, and modern web
                    development practices. He has worked on a variety of projects, including e-commerce platforms, SaaS
                    applications, and enterprise-level web apps. John is known for his attention to detail,
                    problem-solving skills, and ability to collaborate effectively with cross-functional teams.
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
            <div className="grid gap-4 border rounded-lg p-4">
              <div className="flex items-center gap-4">
                <Avatar className="w-12 h-12">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JA</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-semibold">Jane Appleseed</div>
                  <div className="text-sm text-muted-foreground">4 years of experience</div>
                </div>
                <div className="ml-auto flex items-center gap-2">
                  <div className="text-sm font-medium">Relevancy Score</div>
                  <div className="flex items-center gap-1">
                    <div className="w-16 h-4 rounded-full bg-muted">
                      <div className="h-full w-2/3 rounded-full bg-primary" />
                    </div>
                    <div className="text-sm font-medium">65%</div>
                  </div>
                </div>
              </div>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center gap-2 font-medium [&[data-state=open]>svg]:rotate-90">
                  Career Summary
                  <ChevronRightIcon className="w-4 h-4 transition-all" />
                </CollapsibleTrigger>
                <CollapsibleContent>
                  <div className="text-muted-foreground">
                    Jane is a skilled frontend developer with a strong background in React, Redux, and modern web
                    development practices. She has worked on a variety of projects, including e-commerce platforms, SaaS
                    applications, and enterprise-level web apps. Jane is known for her attention to detail,
                    problem-solving skills, and ability to collaborate effectively with cross-functional teams.
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
            <div className="grid gap-4 border rounded-lg p-4">
              <div className="flex items-center gap-4">
                <Avatar className="w-12 h-12">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>SM</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-semibold">Sarah Michaels</div>
                  <div className="text-sm text-muted-foreground">9 years of experience</div>
                </div>
                <div className="ml-auto flex items-center gap-2">
                  <div className="text-sm font-medium">Relevancy Score</div>
                  <div className="flex items-center gap-1">
                    <div className="w-16 h-4 rounded-full bg-muted">
                      <div className="h-full w-4/5 rounded-full bg-primary" />
                    </div>
                    <div className="text-sm font-medium">80%</div>
                  </div>
                </div>
              </div>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center gap-2 font-medium [&[data-state=open]>svg]:rotate-90">
                  Career Summary
                  <ChevronRightIcon className="w-4 h-4 transition-all" />
                </CollapsibleTrigger>
                <CollapsibleContent>
                  <div className="text-muted-foreground">
                    Sarah is an experienced frontend developer with a strong background in React, Redux, and modern web
                    development practices. She has worked on a variety of projects, including e-commerce platforms, SaaS
                    applications, and enterprise-level web apps. Sarah is known for her attention to detail,
                    problem-solving skills, and ability to collaborate effectively with cross-functional teams.
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
